#ifndef VERSION_H_
#define VERSION_H_

/* 0.1.2 */
#define ANTCC_VERSION_MAJOR 0
#define ANTCC_VERSION_MINOR 1
#define ANTCC_VERSION_PATCH 2

#define XSTR_(...) #__VA_ARGS__
#define XSTR(...) XSTR_(__VA_ARGS__)
#define ANTCC_VERSION_STR XSTR(ANTCC_VERSION_MAJOR) "." XSTR(ANTCC_VERSION_MINOR) "." XSTR(ANTCC_VERSION_PATCH)

#endif
