#!/bin/sh

cd "$(dirname "$0")"/..

version=$(cat VERSION)
major=$(echo "$version" | cut -d. -f1)
minor=$(echo "$version" | cut -d. -f2)
patch=$(echo "$version" | cut -d. -f3)

if test -d .git; then
    rev=$(git describe --tags --dirty --match v"$version" 2>/dev/null)
    if [ $? = 0 ]; then
        rev=$(echo "$rev" | sed 's/^v[0-9.]*//')
    else
        rev="-dirty"
    fi
fi

cat <<EOF
/* AUTOGENERATED by tool/gen-version.sh - do not edit */
#define ANTCC_VERSION_MAJOR "$major"
#define ANTCC_VERSION_MINOR "$major"
#define ANTCC_VERSION_PATCH "$major"
#define ANTCC_VERSION_STR "$version$rev"
EOF
