#!/bin/sh

set -e
cat << @
/* AUTOGENERATED by a_embedfilesdir.sh - do not edit */

#include <stddef.h>
#define _ZEROPAD "\0\0\0\0\0"
struct EmbedFile {
   const char *name;
   const char *s;
   size_t len;
} embedfilesdir[] = {
@

H () {
   echo '{"'"$1"'",'
   awk '{ print "\""$0"\\n\""; n+=length+1 }
        END { print "_ZEROPAD, "n"}," }'
}

H stddef.h << @
#pragma once
typedef __PTRDIFF_TYPE__ ptrdiff_t;
typedef __SIZE_TYPE__ size_t;
typedef __WCHAR_TYPE__ wchar_t;
#undef NULL
#define NULL ((void*)0)
#undef offsetof
#define offsetof(type, memb) ((size_t)((char *)&((type *)0)->memb - (char *)0))
#if __STDC_VERSION__ >= 201112L
typedef struct {long long __ll; long double __ld;} max_align_t;
#endif
@

H stdarg.h << @
#pragma once
typedef __builtin_va_list va_list;
#ifndef __GNUC_VA_LIST
#define __GNUC_VA_LIST
typedef __builtin_va_list __gnuc_va_list;
#endif
#define va_start(ap,n)   __builtin_va_start(ap)
#define va_arg(ap,type)  __builtin_va_arg(ap, type)
#define va_copy(dst,src) __builtin_va_copy(dst, src)
#define va_end(ap)       __builtin_va_end(ap)
@

H stdbool.h << @
#pragma once
#if __STDC_VERSION__ < 202311L /* in C23 they are keywords */
#define bool _Bool 
#define true 1
#define false 0
#endif
#define __bool_true_false_are_defined 1
@

H float.h << @
#pragma once
#define FLT_ROUNDS       (-1)
#define FLT_EVAL_METHOD  (-1)
#define FLT_HAS_SUBNORM  (-1)
#define DBL_HAS_SUBNORM  (-1)
#define LDBL_HAS_SUBNORM (-1)
#define FLT_RADIX        2
#define FLT_MANT_DIG     24
#define DBL_MANT_DIG     53
#define LDBL_MANT_DIG    53
#define FLT_DECIMAL_DIG  9
#define DBL_DECIMAL_DIG  17
#define LDBL_DECIMAL_DIG 17
#define DECIMAL_DIG      17
#define FLT_DIG          6
#define DBL_DIG          15
#define LDBL_DIG         15
#define FLT_MIN_EXP      (-125)
#define DBL_MIN_EXP      (-1021)
#define LDBL_MIN_EXP     (-1021)
#define FLT_MIN_10_EXP   (-37)
#define DBL_MIN_10_EXP   (-307)
#define LDBL_MIN_10_EXP  (-307)
#define FLT_MAX_EXP      128
#define DBL_MAX_EXP      1024
#define LDBL_MAX_EXP     1024
#define FLT_MAX_10_EXP   38
#define DBL_MAX_10_EXP   308
#define LDBL_MAX_10_EXP  308
#define FLT_MAX          3.40282e+38
#define DBL_MAX          1.79769e+308
#define LDBL_MAX         1.79769e+308
#define FLT_EPSILON      1.19209e-07
#define DBL_EPSILON      2.22045e-16
#define LDBL_EPSILON     2.22045e-16
#define FLT_MIN          1.17549e-38
#define DBL_MIN          2.22507e-308
#define LDBL_MIN         2.22507e-308
#define FLT_TRUE_MIN     1.4013e-45
#define DBL_TRUE_MIN     4.94066e-324
#define LDBL_TRUE_MIN    4.94066e-324
@

H complex.h << @
#pragma once

#define _Complex_I 1.0iF
#include_next <complex.h>
#undef _Complex_I
#define _Complex_I 1.0iF
@

H iso646.h << @
#define and     &&
#define and_eq  &=
#define bitand  &
#define bitor   |
#define compl   ~
#define not     !
#define not_eq  !=
#define or      ||
#define or_eq   |=
#define xor     ^
#define xor_eq  ^=
@

H stdnoreturn.h << @
#define noreturn _Noreturn
@

H stdalign.h << @
#if __STDC_VERSION__ < 202311L
#define alignas _Alignas
#define alignof _Alignof
#define __alignas_is_defined 1
#define __alignof_is_defined 1
#endif
@

H limits.h << @
#pragma once
/* Tell glibc not to try to recursively #include_next gcc's <limits.h> */
#if defined __GNUC__ && !defined _GCC_LIMITS_H
#define _GCC_LIMITS_H_
#endif
/* We want the system libc header for POSIX constants */
#ifdef __STDC_HOSTED__
#include_next <limits.h>
#endif

#undef CHAR_BIT
#undef CHAR_MAX
#undef CHAR_MIN
#undef UCHAR_MAX
#undef SCHAR_MAX
#undef SCHAR_MIN
#undef USHRT_MAX
#undef SHRT_MAX
#undef SHRT_MIN
#undef MB_LEN_MAX
#undef UINT_MAX
#undef INT_MAX
#undef INT_MIN
#undef ULONG_MAX
#undef LONG_MAX
#undef LONG_MIN
#undef ULLONG_MAX
#undef LLONG_MAX
#undef LLONG_MIN

#define CHAR_BIT    8
#ifdef __CHAR_UNSIGNED__
#define CHAR_MAX    UCHAR_MAX
#define CHAR_MIN    0
#else
#define CHAR_MAX    SCHAR_MAX
#define CHAR_MIN    SCHAR_MIN
#endif
#define UCHAR_MAX   255
#define SCHAR_MAX   127
#define SCHAR_MIN   (-128)
#define USHRT_MAX   65535
#define SHRT_MAX    32767
#define SHRT_MIN    (-32768)
#define MB_LEN_MAX  16
#define UINT_MAX    4294967295U
#define INT_MAX     2147483647
#define INT_MIN     (-INT_MAX - 1)
#if __SIZEOF_LONG__ == __SIZEOF__INT__
#define ULONG_MAX   4294967295UL
#define LONG_MAX    2147483647L
#else
#define ULONG_MAX   18446744073709551615UL
#define LONG_MAX    9223372036854775807L
#endif
#define LONG_MIN    (-LONG_MAX - 1L)
#define ULLONG_MAX  18446744073709551615ULL
#define LLONG_MAX   9223372036854775807LL
#define LLONG_MIN   (-LLONG_MAX-1)
@

cat << @
   {NULL}
};

#ifdef EMBEDFILESDIR_CHECKSIZES
#include <string.h>
#include <stdio.h>
int main() {
   int rc = 0;
   for (int i = 0; embedfilesdir[i].name; ++i) {
      struct EmbedFile *e = &embedfilesdir[i];
      if (strlen(e->s) != e->len) {
         fprintf(stderr, "%s expected %d actual %d\n",
                  e->name, (int)e->len, (int)strlen(e->s));
         ++rc;
      }
   }
   return rc;
}
#endif
@

# vim:set ts=3 sw=3 expandtab:
