/* 0.3.0 */
#define ANTCC_VERSION_MAJOR 0
#define ANTCC_VERSION_MINOR 3
#define ANTCC_VERSION_PATCH 0

#define XSTR_(...) #__VA_ARGS__
#define XSTR(...) XSTR_(__VA_ARGS__)
#define ANTCC_VERSION_STR XSTR(ANTCC_VERSION_MAJOR) "." XSTR(ANTCC_VERSION_MINOR) "." XSTR(ANTCC_VERSION_PATCH)
