when:
  - event: push
    branch: trunk

steps:
  - name: build
    image: debian
    commands:
      - apt-get update && apt-get install -y gcc make
      - ./configure && make
      - ./antcc -v

  - name: test-bootstrap
    image: debian
    commands:
      - apt-get update && apt-get install -y make gcc
      - ./test/bootstrap.sh

  - name: test-run
    image: debian
    commands:
      - apt-get update && apt-get install -y gcc
      - ./test/run.sh --print

    depends_on: [build]

  - name: test-external-metalang99
    image: debian
    commands:
      - apt-get update && apt-get install -y cmake make
      - ./test/external/metalang99.sh
    depends_on: [build]

  - name: test-external-lua
    image: debian
    commands:
      - apt-get update && apt-get install -y gcc
      - apt-get update && apt-get install -y make
      - ./test/external/lua.sh
    depends_on: [build]

